language: scala
scala:
- 2.11.6
script:
- sbt clean "project powerapi-core" coverage test
after_success:
- sbt "project powerapi-core" coverageReport
- sbt "project powerapi-core" codacyCoverage
- sbt "project powerapi-core" coveralls
sudo: false
